# apiVersion: v1
# kind: Pod
# metadata:
#   name: 
# spec:
#   containers:
#   - name: 
#     image: 

apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    name: myapp
    env: development
spec:
  containers:
  - name: myapp
    image: nginx
